### ISSUE TITLE
Implement Next.js server

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/mobile-passport#2]
https://app.dework.xyz/nation3/app-2?taskId=2a5ceb0e-ed0f-43ef-a211-16830aaba13f

> Implement a NextJS server (using TypeScript) implementing the methods detailed at https://github.com/nation3/mobile-passport/blob/main/SPECS.md#api

> Implement the authentication methods explained in the specs as well.

---

## Implement Next.js server
- [x] https://github.com/nation3/mobile-passport/pull/1/commits/6835dbebc265c6baa2770acfe4645a6128528949 refactor: change extensions from .js to .ts
- [x] https://github.com/nation3/mobile-passport/pull/1/commits/ee5a62a0512d6822dfa809f7ca9023c6b439d55b Add ESLint config ("Strict")
- [x] https://github.com/nation3/mobile-passport/pull/1/commits/4ea62d53b31b637ce98852ba862de985e1960b87 Set `strict` TypeScript mode
- [x] https://github.com/nation3/mobile-passport/pull/1/commits/97eca0799d52d4bb620b65433cd17d30b5c57014 Add TypeScript interfaces
  - [x] ApplePass
  - [x] GooglePass

## Server Build and Deployment
- [x] Configure server deployment in Vercel
  - [x] Create new project in Vercel
  - [x] Add environment variables in Vercel
  - [x] https://github.com/nation3/mobile-passport/pull/13
  - [x] https://github.com/nation3/mobile-passport/pull/29
- [x] Configure custom domain for the server (`*.nation3.org`)

## Ethereum Address and Signature
- [x] https://github.com/nation3/mobile-passport/pull/15
- [x] https://github.com/nation3/mobile-passport/pull/16
  - [ ] refactor: https://github.com/nation3/mobile-passport/issues/22
  - [ ] refactor: https://github.com/nation3/mobile-passport/issues/25
- [x] Lookup NFT passport
  - [x] https://github.com/nation3/mobile-passport/pull/24
  - [x] Add Infura endpoint environment variable to Vercel: `INFURA_ENDPOINT`
  - [ ] refactor: https://github.com/nation3/mobile-passport/issues/26
  - [x] https://github.com/nation3/mobile-passport/pull/27
  - [x] https://github.com/nation3/mobile-passport/pull/28
- [x] https://github.com/nation3/mobile-passport/pull/31

## app.nation3.org/citizen
- [x] https://github.com/nation3/app/issues/33

**Comment by aahna-ashina** [comment]
https://github.com/nation3/mobile-passport/blob/main/SPECS.md#protected-endpoints
> Protected endpoints
> Protected by authentication so it can only be called by the designated staff.

@luisivan What type of authentication will this be? A higher-level server authentication protecting each URL, or will the authentication be done in the code itself?

**Comment by luisivan** [comment]
> @luisivan What type of authentication will this be? A higher-level server authentication protecting each URL, or will the authentication be done in the code itself?

I'm thinking even Basic Auth would work, since it will be over HTTPS. Basically we just need a password-protected endpoint

**Comment by aahna-ashina** [comment]
> > @luisivan What type of authentication will this be? A higher-level server authentication protecting each URL, or will the authentication be done in the code itself?
> 
> I'm thinking even Basic Auth would work, since it will be over HTTPS. Basically we just need a password-protected endpoint

@luisivan Got it. Then we can add something like `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` as GitHub repo secrets, and then access them in the code with `process.env.*`.

**Comment by luisivan** [comment]
> > > @luisivan What type of authentication will this be? A higher-level server authentication protecting each URL, or will the authentication be done in the code itself?
> > 
> > 
> > I'm thinking even Basic Auth would work, since it will be over HTTPS. Basically we just need a password-protected endpoint
> 
> @luisivan Got it. Then we can add something like `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` in the Vercel project settings, and then access them in the code with `process.env.*`.
> 
> Implemented it here: [0a5ec99](https://github.com/nation3/mobile-passport/commit/0a5ec99b1dcb48b76fc315b17937d3a515beee65)
> 
> > <img alt="Screen Shot 2022-05-23 at 9 47 33 AM" width="333" src="https://user-images.githubusercontent.com/95955389/169747614-7c90f9a7-380e-45d4-a972-c2caebde8edf.png">

awesome
