### ISSUE TITLE
Next.js NestedMiddlewareError

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/mobile-passport#62]
https://app.dework.xyz/nation3/app-2?taskId=a3354a32-12f8-4078-9edb-0d3e9adf2bf2

Error when upgrading Next.js from 12.1.6 to 12.2.5:

> Build error occurred
NestedMiddlewareError: Nested Middleware is not allowed, found:
pages/api/_middleware
Please move your code to a single file at /middleware instead.
Read More - https://nextjs.org/docs/messages/nested-middleware

_Originally posted by @aahna-ashina in https://github.com/nation3/mobile-passport/pull/51#pullrequestreview-1083625871_

**Comment by sdhacker** [comment]
#65

**Comment by sdhacker** [comment]
#65
