### ISSUE TITLE
Icon displays with black borders

### ISSUE THREAD

**Issue by luisivan** [nation3/mobile-passport#81]
![IMG_7403](https://user-images.githubusercontent.com/718208/191048363-1666c063-dc92-44da-aaf2-7ded97377fd9.jpg)

**Comment by aahna-ashina** [comment]
@luisivan Is there another icon background color than black when you see notifications from other apps?

**Comment by luisivan** [comment]
@aahna-ashina there's no background like this in any other app because they all have the icon with the default iOS border radius (not completely rounded, like the icon we have now).

**Comment by aahna-ashina** [comment]
Fixed:  https://discord.com/channels/690584551239581708/963778898389237800/1055082605512499250
